### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: PDF Library Error: Error during initialization

### ISSUE THREAD

**Issue by pulkit-maheshwr** [datalogics/adobe-pdf-library-samples#81]
Running the Java samples (Annotations.Java) - 

Exception in thread "main" java.lang.RuntimeException: PDF Library Error: Error during initialization, Error number: 1073741825
	at com.datalogics.PDFL.PDFLJNI.new_Library__SWIG_0(Native Method)
	at com.datalogics.PDFL.Library.<init>(Library.java:128)
	at com.datalogics.pdfl.samples.Annotations.Annotations.Annotations.main(Annotations.java:32)

**Comment by pulkit-maheshwr** [comment]
I have already specified the directory in the PATH environment variable. Initially, I was getting some other error.

**Comment by datalogics-pgallot** [comment]
@pulkit-maheshwr please send an Email to tech_support@datalogics.com to continue this conversation off-line.
